services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  T3thi\TranslationHandling\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  T3thi\TranslationHandling\Command\GeneratorCommand:
    tags:
      - name: 'console.command'
        command: 'translation-handling:generate'
        description: 'Generate page tree(s) with translation handling examples'
        schedulable: false

  T3thi\TranslationHandling\Generator\Generator:
    public: true
    arguments:
      - '@T3thi\TranslationHandling\Generator\RecordFinder'
